# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - torso_controller
    - right_arm_controller
    - left_arm_controller
    - right_gripper_controller
    - left_gripper_controller

  torso_controller:
    type: FollowJointTrajectory
    joints:
      - joint_1
      - joint_2
      - joint_3
    action_ns: follow_joint_trajectory
    default: true
  right_arm_controller:
    type: FollowJointTrajectory
    joints:
      - joint_4
      - joint_5
      - joint_6
      - joint_7
    action_ns: follow_joint_trajectory
    default: true
  left_arm_controller:
    type: FollowJointTrajectory
    joints:
      - joint_9
      - joint_10
      - joint_11
      - joint_12
    action_ns: follow_joint_trajectory
    default: true
  right_gripper_controller:
    type: GripperCommand
    joints:
      - joint_8
    action_ns: gripper_cmd
    default: true
  left_gripper_controller:
    type: GripperCommand
    joints:
      - joint_13
    action_ns: gripper_cmd
    default: true